## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  persistence:
    accessModes:
      - ReadWriteOnce
    storageClassName: harvester
    size: 10Gi
    subPath: null
    type: pvc
    annotations: null
    finalizers: null
    enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.loki-stack.svc.cluster.local
      access: proxy
      editable: false
      jsonData:
        maxLines: 1000
        derivedFields: []
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "nimbus"

prometheus:
  prometheusSpec:
    retentionSize: 50GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    
rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx:
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true
